services:

    # MySQL Database service.
    database:
        image: mysql:8.0
        container_name: database
        command: --max_allowed_packet=32505856
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: core
            MYSQL_USER: effendiian
            MYSQL_PASSWORD: secret
        restart: unless-stopped
        ports:
            - '33066:3306'

    adminer:
        depends_on:
            - database
        image: adminer
        restart: always
        ports:
            - '8080:8080'

    web:
        depends_on:
            - database
            - adminer
        container_name: php-apache
        build:
            context: ./web
        volumes:
            - ./src:/var/www/laravel_app
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        environment:
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: core
            DB_USERNAME: effendiian
            DB_PASSWORD: secret
        ports:
            - '8087:80'

volumes:
    db_data: {}